package com.swiftapp.utils

object AppStrings {

    fun get(key: String, language: AppLanguage): String {
        val langMap = translations[language] ?: translations[AppLanguage.ENGLISH] ?: emptyMap()
        return langMap[key] ?: translations[AppLanguage.ENGLISH]?.get(key) ?: key
    }

    private val translations: Map<AppLanguage, Map<String, String>> = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "All Your PDF Tools in One Place",
            "search_placeholder" to "Search file",
            "tab_home" to "Home",
            "tab_tools" to "Tools",
            "tab_settings" to "Settings",
            "subsection_recent" to "Recent",
            "subsection_all_files" to "All Files",
            "menu_open" to "Open",
            "menu_share" to "Share",
            "menu_rename" to "Rename",
            "menu_details" to "Details",
            "menu_delete" to "Delete",
            "menu_more" to "More",
            "menu_back" to "Back",
            "tool_merge" to "Merge PDF",
            "tool_merge_desc" to "Combine multiple PDFs into one.",
            "tool_compress" to "Compress PDF",
            "tool_compress_desc" to "Reduce document file size.",
            "tool_scan" to "Scan to PDF",
            "tool_scan_desc" to "Scan paper documents using camera.",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "Add signature stamp to PDF.",
            "tool_protect" to "Protect PDF",
            "tool_protect_desc" to "Add password encryption.",
            "tool_unlock" to "Unlock PDF",
            "tool_unlock_desc" to "Remove password lock.",
            "tool_image_to_pdf" to "Image to PDF",
            "tool_image_to_pdf_desc" to "Convert photos & images to PDF.",
            "tool_pdf_to_images" to "PDF to Images",
            "tool_pdf_to_images_desc" to "Extract images from pages.",
            "tool_rotate" to "Rotate PDF",
            "tool_rotate_desc" to "Change page orientation.",
            "tool_split" to "Split PDF",
            "tool_split_desc" to "Extract pages into separate PDFs.",
            "tool_delete_pages" to "Delete Pages",
            "tool_delete_pages_desc" to "Remove unwanted pages from PDF.",
            "settings_title" to "Settings",
            "settings_account" to "Account",
            "settings_app" to "App Settings",
            "settings_theme" to "Theme (Dark Mode)",
            "settings_notification" to "Notification",
            "settings_notification_sub" to "Sound and banner alerts on operation complete",
            "settings_storage_permission" to "Storage Access Permission",
            "storage_perm_title" to "Storage Access Status",
            "perm_status_granted" to "All Files Access Granted",
            "perm_status_action_required" to "Action Required",
            "perm_status_limited" to "Partial Access",
            "storage_perm_granted_desc" to "Swift PDF has full storage access to read, save, merge, and edit PDF files anywhere in your storage.",
            "storage_perm_req_desc" to "All-Files storage access is required to discover existing documents, merge large PDFs, and save files to your preferred folders.",
            "btn_open_storage_settings" to "Open Storage Settings",
            "settings_haptic" to "Haptic Feedback",
            "settings_haptic_sub" to "Vibration on touch and actions",
            "settings_naming_convention" to "File Naming Convention",
            "settings_naming_sub" to "Auto-append timestamp to output files",
            "naming_preview_label" to "Sample File Name Preview",
            "naming_auto_timestamp" to "Auto-append Timestamp",
            "naming_auto_timestamp_desc" to "Append timestamp to generated files (e.g. Scan_20260924_0100.pdf)",
            "naming_format_title" to "Timestamp Format",
            "naming_format_compact" to "Compact (yyyyMMdd_HHmm)",
            "naming_format_detailed" to "Detailed (yyyy-MM-dd_HHmmss)",
            "naming_format_date" to "Date Only (yyyyMMdd)",
            "settings_language" to "Language",
            "settings_storage" to "Storage",
            "settings_save_location" to "Default Save Location",
            "settings_save_location_sub" to "Where output PDFs are saved",
            "save_loc_swift" to "Swift Folder (Recommended)",
            "save_loc_downloads" to "Downloads Folder",
            "save_loc_documents" to "Documents / Internal Storage",
            "settings_cloud" to "Cloud Services",
            "settings_dropbox" to "Dropbox",
            "settings_privacy" to "Privacy & Security",
            "settings_app_lock" to "App Lock & Biometrics",
            "settings_app_lock_sub" to "Protect app with Fingerprint, Face Unlock or PIN",
            "lock_type_none" to "Disabled",
            "lock_type_none_desc" to "No lock required to open app",
            "lock_type_pin" to "PIN Passcode",
            "lock_type_pin_set" to "4-Digit PIN configured",
            "lock_type_pin_not_set" to "Tap to set 4-Digit PIN",
            "lock_type_bio" to "Biometric Unlock",
            "lock_type_bio_desc" to "Fingerprint or Face Unlock",
            "lock_type_bio_pin" to "Biometric + PIN Passcode",
            "lock_type_bio_pin_desc" to "Fingerprint with PIN backup",
            "btn_change_pin" to "Change PIN",
            "pin_set_title" to "Set App PIN",
            "pin_set_desc" to "Enter a 4-digit security PIN",
            "pin_confirm_title" to "Confirm PIN",
            "pin_confirm_desc" to "Re-enter your 4-digit PIN",
            "pin_mismatch_error" to "PINs do not match. Try again.",
            "pin_incorrect_error" to "Incorrect PIN. Try again.",
            "lock_screen_subtitle" to "Enter PIN or Biometrics to continue",
            "btn_use_pin" to "Use PIN",
            "btn_unlock_biometrics" to "Unlock with Biometrics",
            "settings_about" to "About Swift PDF",
            "settings_version" to "Version 1.0.0 (2026)",
            "password_enter" to "Enter Password",
            "password_protected_sub" to "This file is protected. Enter password to open.",
            "btn_open" to "Open",
            "btn_cancel" to "Cancel",
            "btn_save" to "Save",
            "btn_done" to "Done",
            "settings_scanner_camera" to "Scanner & Camera",
            "settings_default_filter" to "Default Scan Filter",
            "settings_default_filter_sub" to "Preset filter applied when taking or importing scans",
            "filter_magic_color" to "Magic Color (Enhanced)",
            "filter_bw" to "B&W Document",
            "filter_original" to "Original (Photo)",
            "filter_grayscale" to "Grayscale",
            "settings_shutter_sound" to "Shutter Sound",
            "settings_shutter_sound_sub" to "Play camera capture sound on scan",
            "settings_auto_edge" to "Auto Edge Detection",
            "settings_auto_edge_sub" to "Automatically crop document borders on scan",
            "settings_support_group" to "About & Support",
            "settings_share_app" to "Share App",
            "settings_share_app_sub" to "Share Swift PDF with friends & colleagues",
            "settings_privacy_terms" to "Privacy Policy & Terms",
            "settings_privacy_terms_sub" to "100% offline & local data security disclosure",
            "privacy_dialog_title" to "Privacy & Security Policy",
            "privacy_dialog_subtitle" to "Offline-First & Zero Data Harvesting",
            "settings_contact_dev" to "Contact Developer & Bug Report",
            "settings_contact_dev_sub" to "Send feedback, report issues or logs",
            "contact_dev_title" to "Contact & Support",
            "contact_dev_subtitle" to "We're here to help! Report bugs or request features",
            "btn_send_email_report" to "Email Developer / Bug Report",
            "dialog_select_language" to "Select App Language"
        ),
        AppLanguage.HINDI to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "आपके सभी PDF टूल्स एक जगह",
            "search_placeholder" to "Search file",
            "tab_home" to "होम",
            "tab_tools" to "टूल्स",
            "tab_settings" to "सेटिंग्स",
            "subsection_recent" to "हाल ही में (Recent)",
            "subsection_all_files" to "सभी फाइलें (All Files)",
            "menu_open" to "खोलें (Open)",
            "menu_share" to "शेयर करें (Share)",
            "menu_rename" to "नाम बदलें (Rename)",
            "menu_details" to "विवरण (Details)",
            "menu_delete" to "हटाएं (Delete)",
            "menu_more" to "और टूल्स (More)",
            "menu_back" to "पीछे (Back)",
            "tool_merge" to "PDF मर्ज करें",
            "tool_merge_desc" to "कई PDF को एक में मिलाएं।",
            "tool_compress" to "PDF कंप्रेस करें",
            "tool_compress_desc" to "फाइल का साइज कम करें।",
            "tool_scan" to "PDF स्कैन करें",
            "tool_scan_desc" to "कैमरे से डॉक्यूमेंट स्कैन करें।",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "PDF पर डिजिटल हस्ताक्षर लगाएं।",
            "tool_protect" to "PDF लॉक करें (Protect)",
            "tool_protect_desc" to "पासवर्ड सुरक्षा जोड़ें।",
            "tool_unlock" to "PDF अनलॉक करें",
            "tool_unlock_desc" to "पासवर्ड लॉक हटाएं।",
            "tool_image_to_pdf" to "फोटो से PDF बनाएं",
            "tool_image_to_pdf_desc" to "फोटोज़ को PDF में बदलें।",
            "tool_pdf_to_images" to "PDF से फोटो निकालें",
            "tool_pdf_to_images_desc" to "पेज को इमेज में बदलें।",
            "tool_rotate" to "PDF घुमाएं (Rotate)",
            "tool_rotate_desc" to "पेज की दिशा बदलें।",
            "tool_split" to "PDF अलग करें (Split)",
            "tool_split_desc" to "पेजों को अलग PDF में बांटें।",
            "tool_delete_pages" to "पेज हटाएं (Delete Pages)",
            "tool_delete_pages_desc" to "अनावश्यक पेजों को हटाएं।",
            "settings_title" to "सेटिंग्स",
            "settings_account" to "खाता (Account)",
            "settings_app" to "ऐप सेटिंग्स",
            "settings_theme" to "थीम (डार्क मोड)",
            "settings_notification" to "सूचनाएं (Notifications)",
            "settings_notification_sub" to "फ़ाइल ऑपरेशन पूरा होने पर नोटिफिकेशन और साउंड अलर्ट",
            "settings_storage_permission" to "स्टोरेज एक्सेस अनुमति (Permission)",
            "storage_perm_title" to "स्टोरेज परमिशन स्थिति",
            "perm_status_granted" to "पूर्ण स्टोरेज अनुमति प्राप्त (Granted)",
            "perm_status_action_required" to "अनुमति आवश्यक (Action Required)",
            "perm_status_limited" to "सीमित पहुंच (Partial)",
            "storage_perm_granted_desc" to "Swift PDF के पास आपकी स्टोरेज में PDF फाइलों को पढ़ने, सहेजने, मर्ज और संपादित करने की पूर्ण पहुंच है।",
            "storage_perm_req_desc" to "मौजूदा दस्तावेज़ खोजने, बड़ी PDF फाइलों को मर्ज करने और पसंदीदा फ़ोल्डर में सहेजने के लिए पूर्ण स्टोरेज अनुमति आवश्यक है।",
            "btn_open_storage_settings" to "स्टोरेज सेटिंग्स खोलें",
            "settings_haptic" to "हैप्टिक फीडबैक (वाइब्रेशन)",
            "settings_haptic_sub" to "बटन दबाने और टूल्स पर वाइब्रेशन",
            "settings_naming_convention" to "फ़ाइल नामकरण नियम (Naming)",
            "settings_naming_sub" to "आउटपुट फ़ाइलों में ऑटो-टाइमस्टैम्प जोड़ें",
            "naming_preview_label" to "फ़ाइल नाम का पूर्वावलोकन (Preview)",
            "naming_auto_timestamp" to "ऑटो टाइमस्टैम्प जोड़ें",
            "naming_auto_timestamp_desc" to "बनाई गई फ़ाइलों में टाइमस्टैम्प जोड़ें (उदा. Scan_20260924_0100.pdf)",
            "naming_format_title" to "टाइमस्टैम्प प्रारूप (Format)",
            "naming_format_compact" to "कॉम्पैक्ट (yyyyMMdd_HHmm)",
            "naming_format_detailed" to "विस्तृत (yyyy-MM-dd_HHmmss)",
            "naming_format_date" to "केवल तारीख (yyyyMMdd)",
            "settings_language" to "भाषा (Language)",
            "settings_storage" to "स्टोरेज",
            "settings_save_location" to "डिफ़ॉल्ट सेव लोकेशन",
            "settings_save_location_sub" to "आउटपुट PDF फाइलें कहाँ सेव होंगी",
            "save_loc_swift" to "Swift फ़ोल्डर (सुझावित)",
            "save_loc_downloads" to "डाउनलोड्स फ़ोल्डर (Downloads)",
            "save_loc_documents" to "डॉक्यूमेंट्स / इंटरनल स्टोरेज",
            "settings_cloud" to "क्लाउड सेवाएं",
            "settings_dropbox" to "ड्रॉपबॉक्स",
            "settings_privacy" to "गोपनीयता एवं सुरक्षा (Privacy & Security)",
            "settings_app_lock" to "ऐप लॉक एवं बायोमेट्रिक्स",
            "settings_app_lock_sub" to "फ़िंगरप्रिंट, फ़ेस अनलॉक या पिन से ऐप सुरक्षित करें",
            "lock_type_none" to "अक्षम (Off)",
            "lock_type_none_desc" to "ऐप खोलने के लिए किसी लॉक की आवश्यकता नहीं",
            "lock_type_pin" to "पिन पासकोड (PIN)",
            "lock_type_pin_set" to "4-अंकों का पिन सेट है",
            "lock_type_pin_not_set" to "4-अंकों का पिन सेट करने के लिए टैप करें",
            "lock_type_bio" to "बायोमेट्रिक अनलॉक",
            "lock_type_bio_desc" to "फ़िंगरप्रिंट या फ़ेस अनलॉक",
            "lock_type_bio_pin" to "बायोमेट्रिक + पिन पासकोड",
            "lock_type_bio_pin_desc" to "पिन बैकअप के साथ फ़िंगरप्रिंट",
            "btn_change_pin" to "पिन बदलें",
            "pin_set_title" to "ऐप का पिन सेट करें",
            "pin_set_desc" to "4-अंकों का सुरक्षा पिन दर्ज करें",
            "pin_confirm_title" to "पिन की पुष्टि करें",
            "pin_confirm_desc" to "अपना 4-अंकों का पिन पुनः दर्ज करें",
            "pin_mismatch_error" to "पिन मेल नहीं खाते। पुनः प्रयास करें।",
            "pin_incorrect_error" to "गलत पिन। पुनः प्रयास करें।",
            "lock_screen_subtitle" to "आगे बढ़ने के लिए पिन या बायोमेट्रिक्स का उपयोग करें",
            "btn_use_pin" to "पिन का उपयोग करें",
            "btn_unlock_biometrics" to "बायोमेट्रिक्स से अनलॉक करें",
            "settings_about" to "Swift PDF के बारे में",
            "settings_version" to "संस्करण 1.0.0 (2026)",
            "password_enter" to "पासवर्ड दर्ज करें",
            "password_protected_sub" to "यह फाइल सुरक्षित है। खोलने के लिए पासवर्ड डालें।",
            "btn_open" to "खोलें",
            "btn_cancel" to "रद्द करें",
            "btn_save" to "सहेजें",
            "btn_done" to "संपन्न",
            "settings_scanner_camera" to "स्कैनर एवं कैमरा सेटिंग्स",
            "settings_default_filter" to "डिफ़ॉल्ट स्कैन फ़िल्टर",
            "settings_default_filter_sub" to "स्कैन करते समय अपने आप लागू होने वाला फ़िल्टर",
            "filter_magic_color" to "मैजिक कलर (Magic Color)",
            "filter_bw" to "ब्लैक एंड व्हाइट (B&W)",
            "filter_original" to "मूल फोटो (Original)",
            "filter_grayscale" to "ग्रेस्केल (Grayscale)",
            "settings_shutter_sound" to "कैमरा शटर साउंड",
            "settings_shutter_sound_sub" to "स्कैन क्लिक करते समय साउंड बजाएं",
            "settings_auto_edge" to "ऑटो एज डिटेक्शन (Auto Crop)",
            "settings_auto_edge_sub" to "दस्तावेज़ के किनारों को अपने आप क्रॉप करें",
            "settings_support_group" to "ऐप के बारे में एवं सहायता (About & Support)",
            "settings_share_app" to "ऐप शेयर करें (Share App)",
            "settings_share_app_sub" to "दोस्तों और सहयोगियों के साथ Swift PDF शेयर करें",
            "settings_privacy_terms" to "गोपनीयता नीति एवं शर्तें (Privacy Policy)",
            "settings_privacy_terms_sub" to "100% ऑफलाइन एवं डेटा सुरक्षा प्रकटीकरण",
            "privacy_dialog_title" to "गोपनीयता एवं सुरक्षा नीति",
            "privacy_dialog_subtitle" to "ऑफ़लाइन-प्रथम और शून्य डेटा संग्रहण",
            "settings_contact_dev" to "डेवलपर से संपर्क / बग रिपोर्ट",
            "settings_contact_dev_sub" to "फीडबैक भेजें या समस्या की रिपोर्ट करें",
            "contact_dev_title" to "सहायता एवं संपर्क",
            "contact_dev_subtitle" to "हम आपकी मदद के लिए तैयार हैं! सुझाव या समस्या बताएं",
            "btn_send_email_report" to "ईमेल / बग रिपोर्ट भेजें",
            "dialog_select_language" to "ऐप की भाषा चुनें"
        ),
        AppLanguage.MARATHI to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "तुमची सर्व PDF साधने एकाच ठिकाणी",
            "search_placeholder" to "Search file",
            "tab_home" to "मुख्यपृष्ठ (Home)",
            "tab_tools" to "टूल्स (Tools)",
            "tab_settings" to "सेटिंग्ज (Settings)",
            "subsection_recent" to "नुकतेच (Recent)",
            "subsection_all_files" to "सर्व फायली (All Files)",
            "menu_open" to "उघडा (Open)",
            "menu_share" to "शेअर करा (Share)",
            "menu_rename" to "नाव बदला (Rename)",
            "menu_details" to "तपशील (Details)",
            "menu_delete" to "हटवा (Delete)",
            "menu_more" to "अधिक (More)",
            "menu_back" to "मागे (Back)",
            "tool_merge" to "PDF एकत्र करा (Merge)",
            "tool_merge_desc" to "एकाधिक PDF एकत्र करा.",
            "tool_compress" to "PDF कॉम्प्रेस करा",
            "tool_compress_desc" to "फाइलचा आकार कमी करा.",
            "tool_scan" to "PDF स्कॅन करा",
            "tool_scan_desc" to "कॅमेऱ्याने दस्तऐवज स्कॅन करा.",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "PDF वर स्वाक्षरी जोडा.",
            "tool_protect" to "PDF लॉक करा (Protect)",
            "tool_protect_desc" to "पासवर्ड सुरक्षा जोडा.",
            "tool_unlock" to "PDF अनलॉक करा",
            "tool_unlock_desc" to "पासवर्ड लॉक काढा.",
            "tool_image_to_pdf" to "फोटोमधून PDF बनवा",
            "tool_image_to_pdf_desc" to "चित्रे PDF मध्ये रूपांतरित करा.",
            "tool_pdf_to_images" to "PDF मधून फोटो काढा",
            "tool_pdf_to_images_desc" to "पेज फोटोमध्ये रूपांतरित करा.",
            "tool_rotate" to "PDF फिरवा (Rotate)",
            "tool_rotate_desc" to "पेजची दिशा बदला.",
            "tool_split" to "PDF विभाजित करा (Split)",
            "tool_split_desc" to "पेज वेगवेगळ्या PDF मध्ये वेगळे करा.",
            "tool_delete_pages" to "पेज हटवा (Delete Pages)",
            "tool_delete_pages_desc" to "नको असलेले पेज काढून टाका.",
            "settings_title" to "सेटिंग्ज",
            "settings_account" to "खाते (Account)",
            "settings_app" to "अ‍ॅप सेटिंग्ज",
            "settings_theme" to "थीम (डार्क मोड)",
            "settings_notification" to "सूचना (Notification)",
            "settings_language" to "भाषा (Language)",
            "settings_storage" to "स्टोरेज",
            "settings_cloud" to "क्लाउड सेवा",
            "settings_dropbox" to "ड्रॉपबॉक्स",
            "settings_privacy" to "गोपनीयता",
            "settings_about" to "Swift PDF बद्दल",
            "settings_version" to "आवृत्ती 1.0.0 (2026)",
            "password_enter" to "पासवर्ड प्रविष्ट करा",
            "password_protected_sub" to "ही फाइल सुरक्षित आहे. उघडण्यासाठी पासवर्ड टाका.",
            "btn_open" to "उघडा",
            "btn_cancel" to "रद्द करा",
            "btn_save" to "जतन करा",
            "btn_done" to "पूर्ण",
            "dialog_select_language" to "अ‍ॅपची भाषा निवडा"
        ),
        AppLanguage.BENGALI to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "আপনার সমস্ত PDF টুল এক জায়গায়",
            "search_placeholder" to "Search file",
            "tab_home" to "হোম",
            "tab_tools" to "টুলস",
            "tab_settings" to "সেটিংস",
            "subsection_recent" to "সাম্প্রতিক (Recent)",
            "subsection_all_files" to "সমস্ত ফাইল (All Files)",
            "menu_open" to "খুলুন (Open)",
            "menu_share" to "শেয়ার করুন (Share)",
            "menu_rename" to "নাম পরিবর্তন (Rename)",
            "menu_details" to "বিবরণ (Details)",
            "menu_delete" to "মুছুন (Delete)",
            "menu_more" to "আরও (More)",
            "menu_back" to "পিছনে (Back)",
            "tool_merge" to "PDF মার্জ করুন",
            "tool_merge_desc" to "একাধিক PDF একত্রিত করুন।",
            "tool_compress" to "PDF কম্প্রেস করুন",
            "tool_compress_desc" to "ফাইলের আকার হ্রাস করুন।",
            "tool_scan" to "PDF স্ক্যান করুন",
            "tool_scan_desc" to "ক্যামেরা দিয়ে স্ক্যান করুন।",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "PDF-এ স্বাক্ষর যোগ করুন।",
            "tool_protect" to "PDF সুরক্ষিত করুন",
            "tool_protect_desc" to "পাসওয়ার্ড লক যোগ করুন।",
            "tool_unlock" to "PDF আনলক করুন",
            "tool_unlock_desc" to "পাসওয়ার্ড লক সরান।",
            "tool_image_to_pdf" to "ছবি থেকে PDF",
            "tool_image_to_pdf_desc" to "ছবিগুলিকে PDF এ রূপান্তর করুন।",
            "tool_pdf_to_images" to "PDF থেকে ছবি",
            "tool_pdf_to_images_desc" to "পৃষ্ঠাগুলি ছবিতে রূপান্তর করুন।",
            "tool_rotate" to "PDF ঘোরান",
            "tool_rotate_desc" to "পৃষ্ঠার অভিযোজন পরিবর্তন করুন।",
            "tool_split" to "PDF বিভক্ত করুন",
            "tool_split_desc" to "পৃষ্ঠাগুলি আলাদা করুন।",
            "tool_delete_pages" to "পৃষ্ঠা মুছুন (Delete Pages)",
            "tool_delete_pages_desc" to "অপ্রয়োজনীয় পৃষ্ঠাগুলি সরান।",
            "settings_title" to "সেটিংস",
            "settings_account" to "অ্যাকাউন্ট",
            "settings_app" to "অ্যাপ সেটিংস",
            "settings_theme" to "থিম (ডার্ক মোড)",
            "settings_notification" to "বিজ্ঞপ্তি",
            "settings_language" to "ভাষা (Language)",
            "settings_storage" to "স্টোরেজ",
            "settings_cloud" to "ক্লাউড সেবা",
            "settings_privacy" to "গোপনীয়তা",
            "settings_about" to "Swift PDF সম্পর্কে",
            "settings_version" to "সংস্করণ 1.0.0 (2026)",
            "password_enter" to "পাসওয়ার্ড লিখুন",
            "password_protected_sub" to "এই ফাইলটি সুরক্ষিত। খুলতে পাসওয়ার্ড লিখুন।",
            "btn_open" to "খুলুন",
            "btn_cancel" to "বাতিল",
            "btn_save" to "সংরক্ষণ",
            "btn_done" to "সম্পন্ন",
            "dialog_select_language" to "অ্যাপের ভাষা নির্বাচন করুন"
        ),
        AppLanguage.GUJARATI to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "તમારા બધા PDF સાધનો એક જ જગ્યાએ",
            "search_placeholder" to "Search file",
            "tab_home" to "હોમ (Home)",
            "tab_tools" to "ટૂલ્સ (Tools)",
            "tab_settings" to "સેટિંગ્સ (Settings)",
            "subsection_recent" to "તાજેતરના (Recent)",
            "subsection_all_files" to "બધી ફાઇલો (All Files)",
            "menu_open" to "ખોલો (Open)",
            "menu_share" to "શેર કરો (Share)",
            "menu_rename" to "નામ બદલો (Rename)",
            "menu_details" to "વિગતો (Details)",
            "menu_delete" to "કાઢી નાખો (Delete)",
            "menu_more" to "વધુ (More)",
            "menu_back" to "પાછળ (Back)",
            "tool_merge" to "PDF મર્જ કરો",
            "tool_merge_desc" to "બહુવિધ PDF ભેગા કરો.",
            "tool_compress" to "PDF કમ્પ્રેસ કરો",
            "tool_compress_desc" to "ફાઇલનું કદ ઘટાડો.",
            "tool_scan" to "PDF સ્કેન કરો",
            "tool_scan_desc" to "કેમેરાથી સ્કેન કરો.",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "PDF પર સહી ઉમેરો.",
            "tool_protect" to "PDF લૉક કરો",
            "tool_protect_desc" to "પાસવર્ડ સુરક્ષા ઉમેરો.",
            "tool_unlock" to "PDF અનલૉક કરો",
            "tool_unlock_desc" to "પાસવર્ડ લૉક દૂર કરો.",
            "tool_image_to_pdf" to "ફોટોમાંથી PDF",
            "tool_image_to_pdf_desc" to "ફોટાઓને PDF માં કન્વર્ટ કરો.",
            "tool_pdf_to_images" to "PDF માંથી ફોટો",
            "tool_pdf_to_images_desc" to "પેજને ફોટામાં કન્વર્ટ કરો.",
            "tool_rotate" to "PDF ફેરવો (Rotate)",
            "tool_rotate_desc" to "પેજની દિશા બદલો.",
            "tool_split" to "PDF વિભાજિત કરો (Split)",
            "tool_split_desc" to "પેજને અલગ PDF માં વહેંચો.",
            "tool_delete_pages" to "પેજ કાઢી નાખો (Delete Pages)",
            "tool_delete_pages_desc" to "અનિચ્છનીય પેજ દૂર કરો.",
            "settings_title" to "સેટિંગ્સ",
            "settings_account" to "ખાતું",
            "settings_app" to "એપ્લિકેશન સેટિંગ્સ",
            "settings_theme" to "થીમ (ડાર્ક મોડ)",
            "settings_notification" to "સૂચનાઓ",
            "settings_language" to "ભાષા (Language)",
            "settings_storage" to "સ્ટોરેજ",
            "settings_cloud" to "ક્લાઉડ સેવાઓ",
            "settings_privacy" to "ગોપનીયતા",
            "settings_about" to "Swift PDF વિશે",
            "settings_version" to "આવૃત્તિ 1.0.0 (2026)",
            "password_enter" to "પાસવર્ડ દાખલ કરો",
            "password_protected_sub" to "આ ફાઇલ સુરક્ષિત છે. ખોલવા માટે પાસવર્ડ દાખલ કરો.",
            "btn_open" to "ખોલો",
            "btn_cancel" to "રદ કરો",
            "btn_save" to "સાચવો",
            "btn_done" to "પૂર્ણ",
            "dialog_select_language" to "એપ્લિકેશનની ભાષા પસંદ કરો"
        ),
        AppLanguage.TAMIL to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "உங்கள் அனைத்து PDF கருவிகளும் ஒரே இடத்தில்",
            "search_placeholder" to "Search file",
            "tab_home" to "முகப்பு (Home)",
            "tab_tools" to "கருவிகள் (Tools)",
            "tab_settings" to "அமைப்புகள் (Settings)",
            "subsection_recent" to "சமீபத்தியவை (Recent)",
            "subsection_all_files" to "அனைத்து கோப்புகள் (All Files)",
            "menu_open" to "திற (Open)",
            "menu_share" to "பகிர் (Share)",
            "menu_rename" to "பெயர் மாற்று (Rename)",
            "menu_details" to "விவரங்கள் (Details)",
            "menu_delete" to "நீக்கு (Delete)",
            "menu_more" to "மேலும் (More)",
            "menu_back" to "பின்செல் (Back)",
            "tool_merge" to "PDF இணைக்க (Merge)",
            "tool_merge_desc" to "பல PDF-களை ஒன்றாக இணைக்கவும்.",
            "tool_compress" to "PDF சுருக்க (Compress)",
            "tool_compress_desc" to "கோப்பின் அளவைக் குறைக்கவும்.",
            "tool_scan" to "PDF ஸ்கேன் செய்க",
            "tool_scan_desc" to "கேமரா மூலம் ஆவணங்களை ஸ்கேன் செய்யவும்.",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "PDF-ல் கையொப்பம் சேர்க்கவும்.",
            "tool_protect" to "PDF பூட்டு (Protect)",
            "tool_protect_desc" to "கடவுச்சொல் பூட்டு சேர்க்கவும்.",
            "tool_unlock" to "PDF திறக்க (Unlock)",
            "tool_unlock_desc" to "கடவுச்சொல் பூட்டை நீக்கவும்.",
            "tool_image_to_pdf" to "புகைப்படம் to PDF",
            "tool_image_to_pdf_desc" to "படங்களை PDF ஆக மாற்றவும்.",
            "tool_pdf_to_images" to "PDF to புகைப்படங்கள்",
            "tool_pdf_to_images_desc" to "பக்கங்களை படங்களாக மாற்றவும்.",
            "tool_rotate" to "PDF சுழற்றுக (Rotate)",
            "tool_rotate_desc" to "பக்க திசையை மாற்றவும்.",
            "tool_split" to "PDF பிரிக்க (Split)",
            "tool_split_desc" to "பக்கங்களை தனித்தனி PDF-களாக பிரிக்கவும்.",
            "tool_delete_pages" to "பக்கங்களை நீக்கு (Delete Pages)",
            "tool_delete_pages_desc" to "தேவையற்ற பக்கங்களை நீக்கவும்.",
            "settings_title" to "அமைப்புகள்",
            "settings_account" to "கணக்கு",
            "settings_app" to "செயலி அமைப்புகள்",
            "settings_theme" to "தீம் (டார்க் மோட்)",
            "settings_notification" to "அறிவிப்புகள்",
            "settings_language" to "மொழி (Language)",
            "settings_storage" to "சேமிப்பகம்",
            "settings_cloud" to "கிளவுட் சேவைகள்",
            "settings_privacy" to "தனியுரிமை",
            "settings_about" to "Swift PDF பற்றி",
            "settings_version" to "பதிப்பு 1.0.0 (2026)",
            "password_enter" to "கடவுச்சொல்லை உள்ளிடவும்",
            "password_protected_sub" to "இந்தக் கோப்பு பாதுகாப்பானது. திறக்க கடவுச்சொல்லை உள்ளிடவும்.",
            "btn_open" to "திறக்க",
            "btn_cancel" to "ரத்து செய்",
            "btn_save" to "சேமி",
            "btn_done" to "முடிந்தது",
            "dialog_select_language" to "பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்"
        ),
        AppLanguage.TELUGU to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "మీ అన్ని PDF సాధనాలు ఒకే చోట",
            "search_placeholder" to "Search file",
            "tab_home" to "హోమ్ (Home)",
            "tab_tools" to "టూల్స్ (Tools)",
            "tab_settings" to "సెట్టింగ్స్ (Settings)",
            "subsection_recent" to "ఇటీవలి (Recent)",
            "subsection_all_files" to "అన్ని ఫైల్స్ (All Files)",
            "menu_open" to "తెరవండి (Open)",
            "menu_share" to "షేర్ చేయండి (Share)",
            "menu_rename" to "పేరు మార్చండి (Rename)",
            "menu_details" to "వివరాలు (Details)",
            "menu_delete" to "తొలగించండి (Delete)",
            "menu_more" to "మరిన్ని (More)",
            "menu_back" to "వెనుకకు (Back)",
            "tool_merge" to "PDF విలీనం (Merge)",
            "tool_merge_desc" to "బహుళ PDF లను ఒకటిగా కలపండి.",
            "tool_compress" to "PDF కుదించండి (Compress)",
            "tool_compress_desc" to "ఫైల్ పరిమాణాన్ని తగ్గించండి.",
            "tool_scan" to "PDF స్కాన్ చేయండి",
            "tool_scan_desc" to "కెమెరాతో స్కాన్ చేయండి.",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "PDF లో సంతకాన్ని జోడించండి.",
            "tool_protect" to "PDF రక్షించండి (Protect)",
            "tool_protect_desc" to "పాస్‌వర్డ్ భద్రతను జోడించండి.",
            "tool_unlock" to "PDF అన్‌లాక్ చేయండి",
            "tool_unlock_desc" to "పాస్‌వర్డ్ లాక్ తొలగించండి.",
            "tool_image_to_pdf" to "ఫోటోల నుండి PDF",
            "tool_image_to_pdf_desc" to "ఫోటోలను PDF గా మార్చండి.",
            "tool_pdf_to_images" to "PDF నుండి ఫోటోలు",
            "tool_pdf_to_images_desc" to "పేజీలను చిత్రాలుగా మార్చండి.",
            "tool_rotate" to "PDF తిప్పండి (Rotate)",
            "tool_rotate_desc" to "పేజీ దిశను మార్చండి.",
            "tool_split" to "PDF విభజించండి (Split)",
            "tool_split_desc" to "పేజీలను ప్రత్యేక PDF లుగా వేరు చేయండి.",
            "tool_delete_pages" to "పేజీలను తొలగించండి (Delete Pages)",
            "tool_delete_pages_desc" to "అనవసరమైన పేజీలను తొలగించండి.",
            "settings_title" to "సెట్టింగ్స్",
            "settings_account" to "ఖాతా",
            "settings_app" to "యాప్ సెట్టింగ్స్",
            "settings_theme" to "థీమ్ (డార్క్ మోడ్)",
            "settings_notification" to "నోటిఫికేషన్లు",
            "settings_language" to "భాష (Language)",
            "settings_storage" to "స్టోరేజ్",
            "settings_cloud" to "క్లౌడ్ సేవలు",
            "settings_privacy" to "గోప్యత",
            "settings_about" to "Swift PDF గురించి",
            "settings_version" to "వెర్షన్ 1.0.0 (2026)",
            "password_enter" to "పాస్‌వర్డ్ నమోదు చేయండి",
            "password_protected_sub" to "ఈ ఫైల్ సురక్షితమైనది. తెరవడానికి పాస్‌వర్డ్ నమోదు చేయండి.",
            "btn_open" to "తెరవండి",
            "btn_cancel" to "రద్దు చేయండి",
            "btn_save" to "సేవ్ చేయండి",
            "btn_done" to "పూర్తయింది",
            "dialog_select_language" to "యాప్ భాషను ఎంచుకోండి"
        ),
        AppLanguage.KANNADA to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "ನಿಮ್ಮ ಎಲ್ಲಾ PDF ಪರಿಕರಗಳು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ",
            "search_placeholder" to "Search file",
            "tab_home" to "ಮುಖಪುಟ (Home)",
            "tab_tools" to "ಪರಿಕರಗಳು (Tools)",
            "tab_settings" to "ಸೆಟ್ಟಿಂಗ್ಸ್ (Settings)",
            "subsection_recent" to "ಇತ್ತೀಚಿನ (Recent)",
            "subsection_all_files" to "ಎಲ್ಲಾ ಫೈಲ್‌ಗಳು (All Files)",
            "menu_open" to "ತೆರೆಯಿರಿ (Open)",
            "menu_share" to "ಹಂಚಿಕೊಳ್ಳಿ (Share)",
            "menu_rename" to "ಹೆಸರು ಬದಲಾಯಿಸಿ (Rename)",
            "menu_details" to "ವಿವರಗಳು (Details)",
            "menu_delete" to "ಅಳಿಸಿ (Delete)",
            "menu_more" to "ಇನ್ನಷ್ಟು (More)",
            "menu_back" to "ಹಿಂದಕ್ಕೆ (Back)",
            "tool_merge" to "PDF ವಿಲೀನಗೊಳಿಸಿ (Merge)",
            "tool_merge_desc" to "ಬಹು PDF ಗಳನ್ನು ಒಂದಾಗಿ ಸೇರಿಸಿ.",
            "tool_compress" to "PDF ಕುಗ್ಗಿಸಿ (Compress)",
            "tool_compress_desc" to "ಫೈಲ್ ಗಾತ್ರವನ್ನು ಕಡಿಮೆ ಮಾಡಿ.",
            "tool_scan" to "PDF ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
            "tool_scan_desc" to "ಕ್ಯಾಮೆರಾದೊಂದಿಗೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ.",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "PDF ಗೆ ಸಹಿ ಸೇರಿಸಿ.",
            "tool_protect" to "PDF ರಕ್ಷಿಸಿ (Protect)",
            "tool_protect_desc" to "ಪಾಸ್‌ವರ್ಡ್ ಲಾಕ್ ಸೇರಿಸಿ.",
            "tool_unlock" to "PDF ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
            "tool_unlock_desc" to "ಪಾಸ್‌ವರ್ಡ್ ಲಾಕ್ ತೆಗೆದುಹಾಕಿ.",
            "tool_image_to_pdf" to "ಚಿತ್ರದಿಂದ PDF",
            "tool_image_to_pdf_desc" to "ಫೋಟೋಗಳನ್ನು PDF ಗೆ ಪರಿವರ್ತಿಸಿ.",
            "tool_pdf_to_images" to "PDF ನಿಂದ ಚಿತ್ರಗಳು",
            "tool_pdf_to_images_desc" to "ಪುಟಗಳನ್ನು ಚಿತ್ರಗಳಾಗಿ ಪರಿವರ್ತಿಸಿ.",
            "tool_rotate" to "PDF ತಿರುಗಿಸಿ (Rotate)",
            "tool_rotate_desc" to "ಪುಟದ ದೃಷ್ಟಿಕೋನವನ್ನು ಬದಲಾಯಿಸಿ.",
            "tool_split" to "PDF ವಿಭಜಿಸಿ (Split)",
            "tool_split_desc" to "ಪುಟಗಳನ್ನು ಪ್ರತ್ಯೇಕ PDF ಗಳಾಗಿ ವಿಭಜಿಸಿ.",
            "tool_delete_pages" to "ಪುಟಗಳನ್ನು ಅಳಿಸಿ (Delete Pages)",
            "tool_delete_pages_desc" to "ಬೇಡದ ಪುಟಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.",
            "settings_title" to "ಸೆಟ್ಟಿಂಗ್ಸ್",
            "settings_account" to "ಖಾತೆ",
            "settings_app" to "ಅಪ್ಲಿಕೇಶನ್ ಸೆಟ್ಟಿಂಗ್ಸ್",
            "settings_theme" to "ಥೀಮ್ (ಡಾರ್ಕ್ ಮೋಡ್)",
            "settings_notification" to "ಅಧಿಸೂಚನೆಗಳು",
            "settings_language" to "ಭಾಷೆ (Language)",
            "settings_storage" to "ಸಂಗ್ರಹಣೆ",
            "settings_cloud" to "ಕ್ಲೌಡ್ ಸೇವೆಗಳು",
            "settings_privacy" to "ಗೌಪ್ಯತೆ",
            "settings_about" to "Swift PDF ಬಗ್ಗೆ",
            "settings_version" to "ಆವೃತ್ತಿ 1.0.0 (2026)",
            "password_enter" to "ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ",
            "password_protected_sub" to "ಈ ಫೈಲ್ ಸುರಕ್ಷಿತವಾಗಿದೆ. ತೆರೆಯಲು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ.",
            "btn_open" to "ತೆರೆಯಿರಿ",
            "btn_cancel" to "ರದ್ದುಮಾಡಿ",
            "btn_save" to "ಉಳಿಸಿ",
            "btn_done" to "ಮುಗಿದಿದೆ",
            "dialog_select_language" to "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ"
        ),
        AppLanguage.PUNJABI to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "ਤੁਹਾਡੇ ਸਾਰੇ PDF ਟੂਲ ਇੱਕੋ ਥਾਂ 'ਤੇ",
            "search_placeholder" to "Search file",
            "tab_home" to "ਹੋਮ (Home)",
            "tab_tools" to "ਟੂਲਸ (Tools)",
            "tab_settings" to "ਸੈਟਿੰਗਾਂ (Settings)",
            "subsection_recent" to "ਹਾਲੀਆ (Recent)",
            "subsection_all_files" to "ਸਾਰੀਆਂ ਫਾਈਲਾਂ (All Files)",
            "menu_open" to "ਖੋਲ੍ਹੋ (Open)",
            "menu_share" to "ਸਾਂਝਾ ਕਰੋ (Share)",
            "menu_rename" to "ਨਾਮ ਬਦਲੋ (Rename)",
            "menu_details" to "ਵੇਰਵੇ (Details)",
            "menu_delete" to "ਮਿਟਾਓ (Delete)",
            "menu_more" to "ਹੋਰ (More)",
            "menu_back" to "ਵਾਪਸ (Back)",
            "tool_merge" to "PDF ਮਿਲਾਓ (Merge)",
            "tool_merge_desc" to "ਕਈ PDF ਨੂੰ ਇੱਕ ਵਿੱਚ ਜੋੜੋ।",
            "tool_compress" to "PDF ਕੰਪਰੈੱਸ ਕਰੋ",
            "tool_compress_desc" to "ਫਾਈਲ ਦਾ ਆਕਾਰ ਘਟਾਓ।",
            "tool_scan" to "PDF ਸਕੈਨ ਕਰੋ",
            "tool_scan_desc" to "ਕੈਮਰੇ ਨਾਲ ਸਕੈਨ ਕਰੋ।",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "PDF 'ਤੇ ਦਸਤਖਤ ਸ਼ਾਮਲ ਕਰੋ।",
            "tool_protect" to "PDF ਲਾਕ ਕਰੋ (Protect)",
            "tool_protect_desc" to "ਪਾਸਵਰਡ ਸੁਰੱਖਿਆ ਜੋੜੋ।",
            "tool_unlock" to "PDF ਅਨਲੌਕ ਕਰੋ",
            "tool_unlock_desc" to "ਪਾਸਵਰਡ ਲਾਕ ਹਟਾਓ।",
            "tool_image_to_pdf" to "ਫੋਟੋ ਤੋਂ PDF",
            "tool_image_to_pdf_desc" to "ਫੋਟੋਆਂ ਨੂੰ PDF ਵਿੱਚ ਬਦਲੋ।",
            "tool_pdf_to_images" to "PDF ਤੋਂ ਫੋਟੋਆਂ",
            "tool_pdf_to_images_desc" to "ਪੰਨਿਆਂ ਨੂੰ ਫੋਟੋਆਂ ਵਿੱਚ ਬਦਲੋ।",
            "tool_rotate" to "PDF ਘੁਮਾਓ (Rotate)",
            "tool_rotate_desc" to "ਪੰਨੇ ਦੀ ਦਿਸ਼ਾ ਬਦਲੋ।",
            "tool_split" to "PDF ਵੰਡੋ (Split)",
            "tool_split_desc" to "ਪੰਨਿਆਂ ਨੂੰ ਵੱਖ-ਵੱਖ PDF ਵਿੱਚ ਵੰਡੋ।",
            "tool_delete_pages" to "ਪੰਨੇ ਮਿਟਾਓ (Delete Pages)",
            "tool_delete_pages_desc" to "ਅਣਚਾਹੇ ਪੰਨੇ ਹਟਾਓ।",
            "settings_title" to "ਸੈਟਿੰਗਾਂ",
            "settings_account" to "ਖਾਤਾ",
            "settings_app" to "ਐਪ ਸੈਟਿੰਗਾਂ",
            "settings_theme" to "ਥੀਮ (ਡਾਰਕ ਮੋਡ)",
            "settings_notification" to "ਸੂਚਨਾਵਾਂ",
            "settings_language" to "ਭਾਸ਼ਾ (Language)",
            "settings_storage" to "ਸਟੋਰੇਜ",
            "settings_cloud" to "ਕਲਾਊਡ ਸੇਵਾਵਾਂ",
            "settings_privacy" to "ਗੋਪਨੀਯਤਾ",
            "settings_about" to "Swift PDF ਬਾਰੇ",
            "settings_version" to "ਵਰਜਨ 1.0.0 (2026)",
            "password_enter" to "ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
            "password_protected_sub" to "ਇਹ ਫਾਈਲ ਸੁਰੱਖਿਅਤ ਹੈ। ਖੋਲ੍ਹਣ ਲਈ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ।",
            "btn_open" to "ਖੋਲ੍ਹੋ",
            "btn_cancel" to "ਰੱਦ ਕਰੋ",
            "btn_save" to "ਸੰਭਾਲੋ",
            "btn_done" to "ਸੰਪੰਨ",
            "dialog_select_language" to "ਐਪ ਦੀ ਭਾਸ਼ਾ ਚੁਣੋ"
        ),
        AppLanguage.MALAYALAM to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "നിങ്ങളുടെ എല്ലാ PDF ടൂളുകളും ഒരിടത്ത്",
            "search_placeholder" to "Search file",
            "tab_home" to "ഹോം (Home)",
            "tab_tools" to "ടൂളുകൾ (Tools)",
            "tab_settings" to "ക്രമീകരണങ്ങൾ (Settings)",
            "subsection_recent" to "സമീപകാല (Recent)",
            "subsection_all_files" to "എല്ലാ ഫയലുകളും (All Files)",
            "menu_open" to "തുറക്കുക (Open)",
            "menu_share" to "പങ്കിടുക (Share)",
            "menu_rename" to "പേര് മാറ്റുക (Rename)",
            "menu_details" to "വിശദാംശങ്ങൾ (Details)",
            "menu_delete" to "ഇല്ലാതാക്കുക (Delete)",
            "menu_more" to "കൂടുതൽ (More)",
            "menu_back" to "തിരികെ (Back)",
            "tool_merge" to "PDF ലയിപ്പിക്കുക (Merge)",
            "tool_merge_desc" to "ഒന്നിലധികം PDF-കൾ ഒന്നാക്കുക.",
            "tool_compress" to "PDF ചുരുക്കുക (Compress)",
            "tool_compress_desc" to "ഫയൽ വലുപ്പം കുറയ്ക്കുക.",
            "tool_scan" to "PDF സ്കാൻ ചെയ്യുക",
            "tool_scan_desc" to "ക്യാമറ ഉപയോഗിച്ച് സ്കാൻ ചെയ്യുക.",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "PDF-ൽ ഒപ്പ് ചേർക്കുക.",
            "tool_protect" to "PDF ലോക്ക് ചെയ്യുക (Protect)",
            "tool_protect_desc" to "പാസ്‌വേഡ് സുരക്ഷ ചേർക്കുക.",
            "tool_unlock" to "PDF അൺലോക്ക് ചെയ്യുക",
            "tool_unlock_desc" to "പാസ്‌വേഡ് ലോക്ക് നീക്കംചെയ്യുക.",
            "tool_image_to_pdf" to "ചിത്രത്തിൽ നിന്ന് PDF",
            "tool_image_to_pdf_desc" to "ചിത്രങ്ങൾ PDF ആക്കി മാറ്റുക.",
            "tool_pdf_to_images" to "PDF-ൽ നിന്ന് ചിത്രങ്ങൾ",
            "tool_pdf_to_images_desc" to "പേജുകൾ ചിത്രങ്ങളാക്കി മാറ്റുക.",
            "tool_rotate" to "PDF തിരിക്കുക (Rotate)",
            "tool_rotate_desc" to "പേജ് ദിശ മാറ്റുക.",
            "tool_split" to "PDF വിഭജിക്കുക (Split)",
            "tool_split_desc" to "പേജുകൾ പ്രത്യേക PDF-കളാക്കുക.",
            "tool_delete_pages" to "പേജുകൾ ഒഴിവാക്കുക (Delete Pages)",
            "tool_delete_pages_desc" to "ആവശ്യമില്ലാത്ത പേജുകൾ നീക്കംചെയ്യുക.",
            "settings_title" to "ക്രമീകരണങ്ങൾ",
            "settings_account" to "അക്കൗണ്ട്",
            "settings_app" to "ആപ്പ് ക്രമീകരണങ്ങൾ",
            "settings_theme" to "തീം (ഡാർക്ക് മോഡ്)",
            "settings_notification" to "അറിയിപ്പുകൾ",
            "settings_language" to "ഭാഷ (Language)",
            "settings_storage" to "സംഭരണം",
            "settings_cloud" to "ക്ലൗഡ് സേവനങ്ങൾ",
            "settings_privacy" to "സ്വകാര്യത",
            "settings_about" to "Swift PDF കുറിച്ച്",
            "settings_version" to "പതിപ്പ് 1.0.0 (2026)",
            "password_enter" to "പാസ്‌വേഡ് നൽകുക",
            "password_protected_sub" to "ഈ ഫയൽ സുരക്ഷിതമാണ്. തുറക്കാൻ പാസ്‌വേഡ് നൽകുക.",
            "btn_open" to "തുറക്കുക",
            "btn_cancel" to "റദ്ദാക്കുക",
            "btn_save" to "സേവ് ചെയ്യുക",
            "btn_done" to "പൂർത്തിയായി",
            "dialog_select_language" to "ആപ്പ് ഭാഷ തിരഞ്ഞെടുക്കുക"
        ),
        AppLanguage.ODIA to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "ଆପଣଙ୍କ ସମସ୍ତ PDF ଟୁଲ୍ ଗୋଟିଏ ସ୍ଥାନରେ",
            "search_placeholder" to "Search file",
            "tab_home" to "ହୋମ୍ (Home)",
            "tab_tools" to "ଟୁଲ୍ସ (Tools)",
            "tab_settings" to "ସେଟିଙ୍ଗ୍ସ (Settings)",
            "subsection_recent" to "ନିକଟ ଅତୀତ (Recent)",
            "subsection_all_files" to "ସମସ୍ତ ଫାଇଲ୍ (All Files)",
            "menu_open" to "ଖୋଲନ୍ତୁ (Open)",
            "menu_share" to "ସେୟାର କରନ୍ତୁ (Share)",
            "menu_rename" to "ନାମ ବଦଳାନ୍ତୁ (Rename)",
            "menu_details" to "ବିବରଣୀ (Details)",
            "menu_delete" to "ଡିଲିଟ୍ କରନ୍ତୁ (Delete)",
            "menu_more" to "ଅଧିକ (More)",
            "menu_back" to "ପଛକୁ (Back)",
            "tool_merge" to "PDF ମର୍ଜ କରନ୍ତୁ",
            "tool_merge_desc" to "ଏକାଧିକ PDF କୁ ଏକାଠି କରନ୍ତୁ।",
            "tool_compress" to "PDF କମ୍ପ୍ରେସ୍ କରନ୍ତୁ",
            "tool_compress_desc" to "ଫାଇଲ୍ ଆକାର ହ୍ରାସ କରନ୍ତୁ।",
            "tool_scan" to "PDF ସ୍କାନ କରନ୍ତୁ",
            "tool_scan_desc" to "କ୍ୟାମେରା ବ୍ୟବହାର କରି ସ୍କାନ୍ କରନ୍ତୁ।",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "PDF ରେ ଦସ୍ତଖତ ଯୋଡନ୍ତୁ।",
            "tool_protect" to "PDF ସୁରକ୍ଷିତ କରନ୍ତୁ",
            "tool_protect_desc" to "ପାସୱାର୍ଡ ଲକ୍ ଯୋଡନ୍ତୁ।",
            "tool_unlock" to "PDF ଅନଲକ୍ କରନ୍ତୁ",
            "tool_unlock_desc" to "ପାସୱାର୍ଡ ଲକ୍ ହଟାନ୍ତୁ।",
            "tool_image_to_pdf" to "ଫଟୋରୁ PDF",
            "tool_image_to_pdf_desc" to "ଫଟୋଗୁଡିକୁ PDF ରେ ରୂପାନ୍ତର କରନ୍ତୁ।",
            "tool_pdf_to_images" to "PDF ରୁ ଫଟୋ",
            "tool_pdf_to_images_desc" to "ପୃଷ୍ଠାଗୁଡିକୁ ଫଟୋରେ ରୂପାନ୍ତର କରନ୍ତୁ।",
            "tool_rotate" to "PDF ଘୂରାନ୍ତୁ (Rotate)",
            "tool_rotate_desc" to "ପୃଷ୍ଠା ଦିଗ ବଦଳାନ୍ତୁ।",
            "tool_split" to "PDF ବିଭାଜନ କରନ୍ତୁ (Split)",
            "tool_split_desc" to "ପୃଷ୍ଠାଗୁଡିକୁ ପୃଥକ୍ PDF ରେ ବିଭାଜନ କରନ୍ତୁ।",
            "tool_delete_pages" to "ପୃଷ୍ଠା ଡିଲିଟ୍ କରନ୍ତୁ (Delete Pages)",
            "tool_delete_pages_desc" to "ଅଦରକାରୀ ପୃଷ୍ଠାଗୁଡ଼ିକୁ ହଟାନ୍ତୁ।",
            "settings_title" to "ସେଟିଙ୍ଗ୍ସ",
            "settings_account" to "ଖାତା",
            "settings_app" to "ଆପ୍ ସେଟିଙ୍ଗ୍ସ",
            "settings_theme" to "ଥିମ୍ (ଡାର୍କ ମୋଡ୍)",
            "settings_notification" to "ବିଜ୍ଞପ୍ତି",
            "settings_language" to "ଭାଷା (Language)",
            "settings_storage" to "ଷ୍ଟୋରେଜ୍",
            "settings_cloud" to "କ୍ଲାଉଡ୍ ସେବା",
            "settings_privacy" to "ଗୋପନୀୟତା",
            "settings_about" to "Swift PDF ବିଷୟରେ",
            "settings_version" to "ସଂସ୍କରଣ 1.0.0 (2026)",
            "password_enter" to "ପାସୱାର୍ଡ ଦିଅନ୍ତୁ",
            "password_protected_sub" to "ଏହି ଫାଇଲ୍ ସୁରକ୍ଷିତ। ଖୋଲିବାକୁ ପାସୱାର୍ଡ ଦିଅନ୍ତୁ।",
            "btn_open" to "ଖୋଲନ୍ତୁ",
            "btn_cancel" to "ବାତିଲ କରନ୍ତୁ",
            "btn_save" to "ସେଭ୍ କରନ୍ତୁ",
            "btn_done" to "ସମ୍ପନ୍ନ",
            "dialog_select_language" to "ଆପ୍ ଭାଷା ଚୟନ କରନ୍ତୁ"
        ),
        AppLanguage.URDU to mapOf(
            "app_name" to "Swift PDF",
            "tagline" to "آپ کے تمام پی ڈی ایف ٹولز ایک جگہ",
            "search_placeholder" to "Search file",
            "tab_home" to "ہوم (Home)",
            "tab_tools" to "ٹولز (Tools)",
            "tab_settings" to "ترتیبات (Settings)",
            "subsection_recent" to "حالیہ (Recent)",
            "subsection_all_files" to "تمام فائلیں (All Files)",
            "menu_open" to "کھولیں (Open)",
            "menu_share" to "شیئر کریں (Share)",
            "menu_rename" to "نام تبدیل کریں (Rename)",
            "menu_details" to "تفصیلات (Details)",
            "menu_delete" to "حذف کریں (Delete)",
            "menu_more" to "مزید (More)",
            "menu_back" to "پیچھے (Back)",
            "tool_merge" to "پی ڈی ایف ضم کریں (Merge)",
            "tool_merge_desc" to "متعدد پی ڈی ایف کو ایک ساتھ ملا دیں۔",
            "tool_compress" to "پی ڈی ایف سکیڑیں (Compress)",
            "tool_compress_desc" to "فائل کا سائز کم کریں۔",
            "tool_scan" to "پی ڈی ایف اسکین کریں",
            "tool_scan_desc" to "کیمرے سے دستاویزات اسکین کریں۔",
            "tool_esign" to "E-Sign PDF",
            "tool_esign_desc" to "پی ڈی ایف پر دستخط شامل کریں۔",
            "tool_protect" to "پی ڈی ایف لاک کریں (Protect)",
            "tool_protect_desc" to "پاس ورڈ سیکیورٹی شامل کریں۔",
            "tool_unlock" to "پی ڈی ایف انلاک کریں",
            "tool_unlock_desc" to "پاس ورڈ لاک ہٹائیں۔",
            "tool_image_to_pdf" to "تصویر سے پی ڈی ایف",
            "tool_image_to_pdf_desc" to "تصاویر کو پی ڈی ایف میں تبدیل کریں۔",
            "tool_pdf_to_images" to "پی ڈی ایف سے تصاویر",
            "tool_pdf_to_images_desc" to "صفحات کو تصاویر میں تبدیل کریں۔",
            "tool_rotate" to "پی ڈی ایف گھمائیں (Rotate)",
            "tool_rotate_desc" to "صفحہ کا رخ تبدیل کریں۔",
            "tool_split" to "پی ڈی ایف الگ کریں (Split)",
            "tool_split_desc" to "صفحات کو الگ الگ پی ڈی ایف میں تقسیم کریں۔",
            "tool_delete_pages" to "صفحات حذف کریں (Delete Pages)",
            "tool_delete_pages_desc" to "غیر ضروری صفحات کو ہٹا دیں۔",
            "settings_title" to "ترتیبات",
            "settings_account" to "اکاؤنٹ",
            "settings_app" to "ایپ کی ترتیبات",
            "settings_theme" to "تھیم (ڈارک موڈ)",
            "settings_notification" to "اطلاعات",
            "settings_language" to "زبان (Language)",
            "settings_storage" to "سٹوریج",
            "settings_cloud" to "کلاؤڈ سروسز",
            "settings_privacy" to "رازداری",
            "settings_about" to "Swift PDF کے بارے میں",
            "settings_version" to "ورژن 1.0.0 (2026)",
            "password_enter" to "پاس ورڈ درج کریں",
            "password_protected_sub" to "یہ فائل محفوظ ہے۔ کھولنے کے لیے پاس ورڈ درج کریں۔",
            "btn_open" to "کھولیں",
            "btn_cancel" to "منسوخ کریں",
            "btn_save" to "محفوظ کریں",
            "btn_done" to "مکمل",
            "dialog_select_language" to "ایپ کی زبان منتخب کریں"
        )
    )
}
